### ISSUE TITLE
/app/explorer.html: 404 Not found

### ISSUE THREAD

**Issue by swobspace** [kosmas58/pia-docker#13]
I'm running docker-compose with all from this repo. I get the backend and frontend running. The backend is accessible via http://localhost:3000. Calling the frontend via http://localhost:8080 I get a redirect to http://localhost:8080/app/explorer.html and a 404 error from nginx.

Any hint's for further debugging?

**Comment by kosmas58** [comment]
What branch of pia-docker do you use?

**Comment by swobspace** [comment]
I'm using the master branch.

**Comment by kosmas58** [comment]
Hallo Wolfgang,
wir kennen uns aus Nagios Zeiten von der OSMC in Nürnberg. Ist schon ein paar Jahre her. Seit ich DSB bin, mache ich nichts mehr mit Nagios bzw. Icinga.  Wir sind aber beide im Krankenhaus tätig, wenn Du noch bei Marienhaus bist.

Leider kann ich Deinen Fehler leider nicht reproduzieren. Bei mir funktioniert das Ganze.

Gruß aus München 
Kosmas

**Comment by swobspace** [comment]
Workaround gefunden: `http://localhost:8080/index.html` aufrufen.

Wenn ich wie beschrieben `http://localhost:8080` aufrufe erhalte ich einen redirect auf `http://localhost:8008/app/explorer.html`. Im Log steht dann 
```
LINCnil-pia-front | 2019/12/16 13:52:12 [error] 6#6: *2 open() "/var/www/pia/dist/pia/app/
explorer.html" failed (2: No such file or directory), client: 172.22.0.1, server: _, reque
st: "GET /app/explorer.html HTTP/1.1", host: "localhost:8080"
```
Das Unterverzeichnis `app` gibt es aber in dem Frontend-Container gar nicht.
