### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by m4hmudftw** [kosmas58/pia-docker#14]
Hello,

I've installed pia-docker and i'm just using the front part.
However, when i'm trying to import a PIA, after selecting the zip file, nothing happend.

The only log output from LINCnil-pia-front are error about no such file '/var/www/pia/dist/pia/metrics' which is not critical.

Regards

**Comment by kosmas58** [comment]
Hello, 

sorry for my delayed response, but Corona changed my focus. You cannot import the zip file, you have import the pia.json file from inside the zip file.

Rgeards
